# Initially used this Dockerfile to build the minio server on-demand
# Created and published a Docker image already built-in with minio and storage

FROM alpine:3.3
EXPOSE 9000
WORKDIR /root
RUN apk add --update curl \
    && curl https://dl.minio.io/server/minio/release/linux-386/minio > minio \
	&& chmod +x minio \
	&& mkdir storage

CMD ./minio server /root/storage